import type { Metadata } from "next";
import "./styles/layout.css";
import "./styles/typography.css";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Sub Sight",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: LayoutProps) => {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
